#!/bin/bash


# First thing is first, setup some sane security

# Let users in the wheel group be sudoers.
cp config-files/sudoers /etc/sudoers

# Setup a new user named "user"

useradd user
passwd user
usermod -aG wheel user

read -p "Generate ssh key for gerrit? [y/n] " -n 1 -r
echo    # move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
	su user -c "ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''"
    cat /home/user/.ssh/id_rsa.pub
    read -p "Copy the above key into gerrit now. Hit enter to continue..."
    exit
fi


read -p "Do you want to install avahi for mdns (recommended!)? [y/n] " -n 1 -r
echo    # move to a new line

if [[ $REPLY =~ ^[Yy]$ ]]
then
    yum install -y avahi
    cp config-files/avahi-daemon.conf /etc/avahi/avahi-daemon.conf -v
	iptables-restore config-files/iptables-avahi -v
	service messagebus restart # For some reason this is down and avahi fails to start.
	service avahi-daemon start
	echo "Run 'ssh-copy-id user@centos-builder.local' before ssh password " 
else
	iptables-restore config-files/iptables -v
	echo "Run 'ssh-copy-id user@[ip-adddress]' before ssh password " 
fi

# Disallow password authentication
read -p "authentication is disabled (hit enter to continue)"
echo	# move to a new line
cp config-files/sshd_config /etc/ssh/sshd_config
service sshd reload

# Install some repos for convenience sake
# We want ius-release, which contains high quality upstream stable pacakages for centos. The default repos are mostly
# garbage but we need them to build saife stuff. This lets us get utilities and modern packages without overriding 
# anthing available in the base repo unless we explicitly ask for it. For example, the git2u package lets us get a 
# version of git from this century as opposed to the git package in centos 6 that is many versions behind. 

yum install -y epel-release
yum install -y https://rhel6.iuscommunity.org/ius-release.rpm

# Alright now we can get some goodies.

# Installs 
# 1. fish, for the rest of the scripts. 
# 2. git, to checkout code.
wget -P /etc/yum.repos.d/ http://download.opensuse.org/repositories/shells:fish:release:2/CentOS_6/shells:fish:release:2.repo
yum -y install fish 


read -p "Do you want to set fish as user's default shell? [y/n] " -n 1 -r
echo    # move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    chsh -s /usr/bin/fish user
fi


yum install -y git2u-all 
yum groupinstall -y 'Development Tools' --skip-broken  # need --skep-broken because yum complains about gitu, but it works fine.
yum install -y java-1.8.0-openjdk-devel.x86_64

# Discover and set java home. maven will need this set for all users, so put it in /etc/environment.
export JAVA_HOME="$(jrunscript -e 'java.lang.System.out.println(java.lang.System.getProperty("java.home"));')"
echo JAVA_HOME=$JAVA_HOME >> /etc/environment

# Install swig from source for SaifeAdapater
# Need prce
yum install -y pcre-devel
tar -xf Dependencies/swig-*
cd swig-*
./configure
make
make install
cd ..

# Install makepp
yum install -y Dependencies/makepp-*.rpm

# Install protobuf 
tar -xf Dependencies/protobuf-*
cd protobuf-*
./configure
make
make install
cd ..

# Install maven
tar -xf Dependencies/apache-maven-3.0.3-bin.tar.gz -C /opt/
ln -s /opt/apache-maven-3.0.3/bin/mvn /usr/bin